### ISSUE TITLE
Crash when trying to launch the IDE

### ISSUE THREAD

**Issue by g-goessel** [NicoHood/Arduino-IDE-for-Raspberry#1]
I did everything as described in the README but when I try to launch `arduino` as root I have this error : 

```
java.lang.NullPointerException
        at processing.app.BaseNoGui.createToolPreferences(BaseNoGui.java:767)
        at processing.app.BaseNoGui.initPackages(BaseNoGui.java:606)
        at processing.app.Base.<init>(Base.java:256)
        at processing.app.Base.guardedMain(Base.java:198)
        at processing.app.Base.main(Base.java:113)
```

Any idea on how to solve it ?

**Comment by NicoHood** [comment]
Sorry no idea.
You might want to check this out:
https://github.com/arduino/Arduino/issues/3334

Or try the newest build from shortie on the raspberry forums.
